### PR TITLE
Shallow clone of skia

### PR DESCRIPTION
**Pull request by ryuukk**
Before:
``` 
[ryuukk@ark ~]$ time git clone --branch aseprite-m96 https://github.com/aseprite/skia.git
Cloning into 'skia'...
remote: Enumerating objects: 597703, done.
remote: Total 597703 (delta 0), reused 0 (delta 0), pack-reused 597703
Receiving objects: 100% (597703/597703), 481.44 MiB | 2.94 MiB/s, done.
Resolving deltas: 100% (496017/496017), done.

real	2m54.491s
user	1m33.056s
sys	0m16.720s
```

after

```
[ryuukk@ark ~]$ time git clone --depth=1 --branch aseprite-m96 https://github.com/aseprite/skia.git
Cloning into 'skia'...
remote: Enumerating objects: 9477, done.
remote: Counting objects: 100% (9477/9477), done.
remote: Compressing objects: 100% (8041/8041), done.
remote: Total 9477 (delta 1814), reused 3923 (delta 1094), pack-reused 0
Receiving objects: 100% (9477/9477), 51.31 MiB | 3.08 MiB/s, done.
Resolving deltas: 100% (1814/1814), done.

real	0m20.115s
user	0m4.974s
sys	0m1.828s
```

- from 3 minutes down to 20 seconds
- from 481mb down to 51mb

### CODE REVIEW

**Comment by ImperatorStorm** [comment]
I dislike this.
Downloading of sources outside of the `source` section is just asking for package breakage and AUR mods getting mad.
Also, this fails to download the repo to a builderc$ specified sources folder.
This is an issue that needs to be fixed by `makepkg`'s maintainers or a fork of `makepkg`.
Closing.

**Comment by ImperatorStorm** [comment]
Also, see https://wiki.archlinux.org/title/User:Apg#makepkg:_shallow_git_clones

**Comment by ryuukk** [comment]
10 years and they haven't fixed shit, it is very sad they are clueless

**Comment by ryuukk** [comment]
@ImperatorStorm 

What about downloading the source from the zip in the release directly?

https://github.com/aseprite/skia/releases

That'll avoid using git

**Comment by ryuukk** [comment]
No opinion on it? I prefer to ask before submitting another PR

**Pull request closed without merging**
