### PR TITLE
[Aseprite] Use release source for skia instead of cloning the entire repo

### PR DESCRIPTION
**Pull request by ryuukk**
Previous discussion: https://github.com/ImperatorStorm/PKGBUILDs/pull/4

I think using this technique is better

### CODE REVIEW

**Comment by ImperatorStorm** [comment]
mind updating the `.SRCINFO`?

**Comment by ryuukk** [comment]
Thanks, and sorry about the missing edits, it is my first time working on a AUR package, learning everyday!

**Comment by FabioLolix** [comment]
About https://github.com/ImperatorStorm/PKGBUILDs/commit/962ed35368167f0571a7422b904b077e9df3d621, renaming m96-2f1f21b8a9.tar.gz simply to skia.tar.gz make this pkgbuild unsuitable for who is using a common source folder (SRCDEST= in /etc/makepkg.conf)

**Comment by ImperatorStorm** [comment]
> About [962ed35](https://github.com/ImperatorStorm/PKGBUILDs/commit/962ed35368167f0571a7422b904b077e9df3d621), renaming m96-2f1f21b8a9.tar.gz simply to skia.tar.gz make this pkgbuild unsuitable for who is using a common source folder (SRCDEST= in /etc/makepkg.conf)

This has been fixed in later commits, see https://github.com/ImperatorStorm/PKGBUILDs/commit/6731a644f092f1dd6069a893f4e20bb4b74e5367

**Pull request closed without merging**
